タグの詳細ページとフォロー機能を追加
hirocueki/qiita2 pull request #21
Opened 2018-11-29 14:54 UTC by hirocueki

- タグの詳細ページを開ける
- ユーザーがタグをフォローする・解除する機能を実装

2018-11-30 05:50 UTC, shunichi requested changes
見ました。
修正おねがいします。

2018-11-30 05:50 UTC, shunichi commented on app/controllers/tags_controller.rb
> +    @items = Item.tagged_with(@tag_name, any: true)
`any: true` は指定した複数のタグのうち１つでもついているレコードを探すときにつけるオプションのようです。
tagged_with の引数で渡しているタグは１つしかないようなので不要だと思います。

2018-11-30 05:50 UTC, shunichi commented on app/controllers/tags_controller.rb
> +    current_user.save!
- TagsController#show はタグの詳細画面（ログインしているユーザーとは関係ない）
- TagsController#create はログインしているユーザーがタグをフォローする

ログインユーザーに対する処理と、ユーザー独立なタグの処理を同じコントローラに混ぜるのは不自然です。
別のコントローラに分けましょう。

2018-11-30 05:50 UTC, shunichi commented on app/views/tags/_follow_form.html.haml
> +  - if current_user.tag_list.include?(tag_name)
ログインしてないときに tags#show を閲覧するとエラーになります。

2018-11-30 05:50 UTC, shunichi commented on app/controllers/tags_controller.rb
> +  def destroy
ログインしていないときに tags#create, tags#destroy が実行できないように、`before_action` で守っておきましょう。
ビュー側でボタンやリンクを非表示にしておけば、だいたい問題ないですが、簡単なのでコントローラレベルでも守っておきましょう

2018-11-30 05:50 UTC, shunichi commented on app/views/tags/_unfollow.html.haml
> +  = f.submit "フォロー解除", class: "btn btn-danger"
ちなみに、こういうヘルパーメソッドもありますよ。
https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to

2018-11-30 05:50 UTC, shunichi commented on spec/controllers/tags_controller_spec.rb
> +RSpec.describe TagsController, type: :controller do
今すぐテストを書く予定がないなら、ファイルごと消してしまったほうがよいです。
必要になったら足しましょう。

2018-11-30 13:06 UTC, hirocueki commented on app/views/tags/_unfollow.html.haml
> +  = f.submit "フォロー解除", class: "btn btn-danger"
ワンラインで書けるようになって便利です！

「フォロー」ボタンの方は、 `hidden_field_tag` が埋め込まれているので適用できないのかなと思っているのですが、 `button_to` で置き換え可能なのでしょうか？

2018-11-30 13:29 UTC, uekkie commented on app/controllers/tags_controller.rb
> +    @items = Item.tagged_with(@tag_name, any: true)
リファレンスの確認不足でした。

`Item.tagged_with(@tag_name)` に修正しました。

2018-11-30 13:32 UTC, hirocueki commented on app/controllers/tags_controller.rb
> +    current_user.save!
[コントローラを名前空間で分離して責務の分割をする \- Runner in the High](http://izumisy-tech.hatenablog.com/entry/2017/06/17/223627) を参考に、責務単位でコントローラを分割しました。

権限の状態ごとに１つのコントローラが割りあたる形になり、保守、可読性があがったように感じます。

2018-12-03 03:01 UTC, shunichi commented on app/views/tags/_unfollow.html.haml
> +  = f.submit "フォロー解除", class: "btn btn-danger"
hidden_field_tag のパラメータを、クエリパラメータに入れればいけそうなきがします。

```ruby
button_to 'フォロー', tags_path(name: tag_name)
```

2018-12-03 03:03 UTC, shunichi commented on app/views/tags/_unfollow.html.haml
> += button_to "フォロー解除", tag_path(tag_name), method: :delete, local: true, class: "btn btn-danger"
`local: true` 必要でしたか？

APIリファレンスを見ると `local` オプションはなくて、 `remote` オプションがあるので、デフォルトではajaxにならないのではないかと思います。
https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to

2018-12-03 03:32 UTC, shunichi commented on config/routes.rb
> +    resources :tags , only: %i(create destroy), param: :name
users/tags#create でタグが作られるわけではないので、フォローの create や destroy と考えたほうが自然な気がします。
自分だったら 、 tags の下にネストする singular resource を作ります。

```ruby
resources :tags , only: %i(show), param: :name do
  resource :follow, only: %i(create destroy)
end
```


2018-12-03 03:40 UTC, shunichi commented on config/routes.rb
> +    resources :tags , only: %i(create destroy), param: :name
あと、この書き方だと users/tags_controller.rb も tags_controller.rb もURI的には同じ階層になるので、紛らわしいですね。
アクションが重なっていないので、今は動いていますが、アクションを追加したくなったときに衝突しかねないという状況は避けたほうがよいと思います。

もし両方で tags を使いたいのであれば `scope module: :users` ではなく `namespace :users` なら、URIもURIヘルパーメソッド(user_path 等)も衝突しなくなります。

https://qiita.com/blueplanet/items/522cc8364f6cf189ecad

2018-12-03 07:59 UTC, hirocueki commented on app/views/tags/_unfollow.html.haml
> +  = f.submit "フォロー解除", class: "btn btn-danger"
できました！
フォローもアンフォローもすっきり書けて読みやすくなりました 👍

2018-12-03 08:52 UTC, hirocueki commented on config/routes.rb
> +    resources :tags , only: %i(create destroy), param: :name
以下のように修正しました。
コントローラを指定している理由は、**タグをフォローするためのコントローラ**という意味がわかりやすくなるかなと考えてそのようにしてみました。

```ruby
resources :tags , only: %i(show), param: :name do
  resource :follow , only: %i(create destroy), controller: "tags_follow"
end
```

2018-12-03 09:08 UTC, shunichi commented on config/routes.rb
> +    resources :tags , only: %i(create destroy), param: :name
コントローラ名を指定するのではなく、`module: :tags` をつけるという手もあります。

```ruby
resources :tags , only: %i(show), param: :name do
  resource :follow , only: %i(create destroy), module: :tags
end
```

こんな感じになるはずです。

- URI tags/:name/follow
- コントローラー tags/follows_controller.rb
- URIヘルパー tag_follow_path(tag)

2018-12-03 09:11 UTC, shunichi commented on app/views/tags/_unfollow.html.haml
> +  = f.submit "フォロー解除", class: "btn btn-danger"
フォロー、アンフォローのパーシャルが button_to １行になったので、パーシャルではなくインラインに書いてしまってもよいと思います。

2018-12-03 14:31 UTC, hirocueki commented on config/routes.rb
> +    resources :tags , only: %i(create destroy), param: :name
`module`をつかったほうがRailswayだと感じたので、変更しました！

2018-12-04 00:35 UTC, shunichi commented on app/views/tags/show.html.haml
> +  %li.list-group-item= link_to "#{item.title}", user_item_path(item.user, item)
よく見たら、ここ `li` が `ul` と同じレベルになってますね。
`ul` の子にしましょう。

2018-12-04 02:34 UTC, shunichi commented
よいと思います 👍

2018-12-04 02:36 UTC, merged